{"name": "test_login1[loginMsg0-用户名或密码错误]", "status": "failed", "statusDetails": {"message": "AssertionError: assert '用户名或密码错误' != '用户名或密码错误'", "trace": "self = <testcase.sjht_login.test_001_login.TestLogin object at 0x000001BB861225F8>, loginMsg = {'login': 'admin', 'pwd': '123456'}\nreturnMsg = '用户名或密码错误'\n\n    @pytest.mark.parametrize('loginMsg, returnMsg', [(login_data.data, login_data.msg), (login_data.data3, login_data.msg3)])\n    def test_login1(self, loginMsg, returnMsg):\n        msg = self.getresponse_text(loginMsg)\n        msg = json.loads(msg)['msg']\n        print(msg)\n>       assert msg != returnMsg\nE       AssertionError: assert '用户名或密码错误' != '用户名或密码错误'\n\ntestcase\\sjht_login\\test_001_login.py:26: AssertionError"}, "parameters": [{"name": "loginMsg", "value": "{'login': 'admin', 'pwd': '123456'}"}, {"name": "returnMsg", "value": "'用户名或密码错误'"}], "start": 1571903616997, "stop": 1571903617049, "uuid": "917e0ad2-d727-4aac-bc4f-bbbf0b6cdc63", "historyId": "93e902c5726aa5c131f12e66eb74edea", "testCaseId": "7532a2c48e7ad35b12dc9f837cecf54d", "fullName": "testcase.sjht_login.test_001_login.TestLogin#test_login1", "labels": [{"name": "parentSuite", "value": "testcase.sjht_login"}, {"name": "suite", "value": "test_001_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "YC-20190315YFJP"}, {"name": "thread", "value": "4628-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.sjht_login.test_001_login"}]}